/**
 * Dot1Xer Supreme Enterprise Edition - Vendor Configuration
 * Version 4.0.0
 * 
 * This file contains vendor-specific configuration generators
 */

// Vendor configuration generators
const VendorConfigurators = {
    // Generate Cisco IOS configuration
    cisco: {
        ios: function(settings) {
            return `! Cisco IOS 802.1X Configuration
! Generated by Dot1Xer Supreme Enterprise Edition
!
! Global AAA Configuration
aaa new-model
aaa authentication dot1x default group radius
aaa authorization network default group radius
aaa accounting dot1x default start-stop group radius

! RADIUS Server Configuration
radius server ${settings.radiusServer1 || 'PRIMARY'}
 address ipv4 ${settings.radiusServer1 || '10.1.1.1'} auth-port 1812 acct-port 1813
 key ${settings.radiusSecret1 || 'radiuskey1'}
 timeout 5
 retransmit 3

${settings.radiusServer2 ? `
radius server ${settings.radiusServer2 || 'SECONDARY'}
 address ipv4 ${settings.radiusServer2 || '10.1.1.2'} auth-port 1812 acct-port 1813
 key ${settings.radiusSecret2 || 'radiuskey2'}
 timeout 5
 retransmit 3
` : ''}

! RADIUS Server Group
aaa group server radius DOT1X-SERVERS
 server name ${settings.radiusServer1 || 'PRIMARY'}
${settings.radiusServer2 ? ` server name ${settings.radiusServer2 || 'SECONDARY'}` : ''}
 deadtime 15
 load-balance method least-outstanding

! Enable 802.1X Globally
dot1x system-auth-control
authentication mac-move permit

! VLAN Configuration
${settings.authVlan ? `vlan ${settings.authVlan}
 name AUTH_VLAN` : ''}
${settings.unauthVlan ? `vlan ${settings.unauthVlan}
 name UNAUTH_VLAN` : ''}
${settings.guestVlan ? `vlan ${settings.guestVlan}
 name GUEST_VLAN` : ''}
${settings.voiceVlan ? `vlan ${settings.voiceVlan}
 name VOICE_VLAN` : ''}

! Interface Configuration
interface ${settings.interface || 'GigabitEthernet1/0/1'}
 switchport mode access
 switchport access vlan ${settings.authVlan || '1'}
${settings.voiceVlan ? ` switchport voice vlan ${settings.voiceVlan}` : ''}
 dot1x pae authenticator
 dot1x timeout tx-period ${settings.txPeriod || 30}
 dot1x timeout quiet-period ${settings.quietPeriod || 60}
 dot1x timeout reauth-period ${settings.reauthPeriod || 3600}
 dot1x max-reauth-req ${settings.maxReauth || 2}
 authentication event fail action authorize vlan ${settings.unauthVlan || '1'}
 authentication event server dead action authorize vlan ${settings.unauthVlan || '1'}
 authentication event server alive action reinitialize
${settings.hostMode === 'multi-domain' ? ' authentication host-mode multi-domain' : 
  settings.hostMode === 'multi-auth' ? ' authentication host-mode multi-auth' : 
  settings.hostMode === 'multi-host' ? ' authentication host-mode multi-host' : 
  ' authentication host-mode single-host'}
${settings.authMethod === 'mab' ? ' authentication order mab\n authentication priority mab\n mab' : 
  settings.authMethod === 'dot1x-mab' ? ' authentication order dot1x mab\n authentication priority dot1x mab\n dot1x pae authenticator\n mab' : 
  ' authentication order dot1x\n authentication priority dot1x\n dot1x pae authenticator'}
${settings.deploymentMode === 'monitor' ? ' authentication open' : ''}
 authentication port-control auto
 spanning-tree portfast
${settings.guestVlan ? ` dot1x guest-vlan ${settings.guestVlan}` : ''}

! Monitor Configuration Status
! show dot1x all
! show authentication sessions
`;
        },
        
        'ios-xe': function(settings) {
            // Similar to IOS but with some XE-specific commands
            return this.ios(settings) + `
! IOS-XE Specific Commands
access-session attributes filter-list list DEFAULT-list
 device-type
 mac-address
 service-type
access-session accounting attributes filter-spec include list DEFAULT-list
`;
        },
        
        'nx-os': function(settings) {
            return `! Cisco NX-OS 802.1X Configuration
! Generated by Dot1Xer Supreme Enterprise Edition
!
! Enable 802.1X feature
feature dot1x

! AAA Configuration
aaa authentication dot1x default group radius
aaa accounting dot1x default group radius

! RADIUS Server Configuration
radius-server host ${settings.radiusServer1 || '10.1.1.1'} key ${settings.radiusSecret1 || 'radiuskey1'} authentication accounting
${settings.radiusServer2 ? `radius-server host ${settings.radiusServer2 || '10.1.1.2'} key ${settings.radiusSecret2 || 'radiuskey2'} authentication accounting` : ''}
radius-server deadtime 15

! Interface Configuration
interface ${settings.interface || 'Ethernet1/1'}
 switchport mode access
 switchport access vlan ${settings.authVlan || '1'}
 dot1x pae authenticator
 dot1x timeout tx-period ${settings.txPeriod || 30}
 dot1x timeout quiet-period ${settings.quietPeriod || 60}
 dot1x timeout re-authperiod ${settings.reauthPeriod || 3600}
 dot1x max-req ${settings.maxReauth || 2}
 dot1x port-control auto
${settings.hostMode === 'multi-host' ? ' dot1x host-mode multi-host' : ''}
${settings.authMethod === 'mab' ? ' mac-authentication' : ''}
 no shutdown

! Show commands for verification
! show dot1x all
! show dot1x interface ${settings.interface || 'Ethernet1/1'} details
`;
        },
        
        'wlc-9800': function(settings) {
            return `! Cisco WLC 9800 802.1X Configuration
! Generated by Dot1Xer Supreme Enterprise Edition
!
! AAA Configuration
aaa new-model
aaa authentication dot1x DOT1X-AUTH group radius
aaa authorization network DOT1X-AUTH group radius
aaa accounting dot1x DOT1X-ACCT start-stop group radius

! RADIUS Server Configuration
radius server ${settings.radiusServer1 || 'PRIMARY'}
 address ipv4 ${settings.radiusServer1 || '10.1.1.1'} auth-port 1812 acct-port 1813
 key ${settings.radiusSecret1 || 'radiuskey1'}
${settings.radiusServer2 ? `
radius server ${settings.radiusServer2 || 'SECONDARY'}
 address ipv4 ${settings.radiusServer2 || '10.1.1.2'} auth-port 1812 acct-port 1813
 key ${settings.radiusSecret2 || 'radiuskey2'}
` : ''}

! WLAN Configuration
wlan ${settings.wlanName || 'ENTERPRISE-SSID'} ${settings.wlanId || 1} ${settings.wlanSsid || 'ENTERPRISE-SSID'}
 security wpa wpa2
 security wpa wpa2 ciphers aes
 security wpa akm dot1x
 no security wpa akm psk
 security dot1x authentication-list DOT1X-AUTH
 accounting-list DOT1X-ACCT
 no shutdown

! Policy Profile Configuration
wireless profile policy ${settings.policyProfile || 'ENTERPRISE-POLICY'}
 aaa-override
 accounting-list DOT1X-ACCT
 central switching
 vlan ${settings.authVlan || '1'}
 no shutdown

! Policy Tag Configuration
wireless tag policy ${settings.policyTag || 'ENTERPRISE-TAG'}
 wlan ${settings.wlanName || 'ENTERPRISE-SSID'} policy ${settings.policyProfile || 'ENTERPRISE-POLICY'}
`;
        }
    },
    
    // Generate Aruba configurations
    aruba: {
        'aos-cx': function(settings) {
            return `! Aruba AOS-CX 802.1X Configuration
! Generated by Dot1Xer Supreme Enterprise Edition
!
! RADIUS Authentication Configuration
radius-server host ${settings.radiusServer1 || '10.1.1.1'} key ${settings.radiusSecret1 || 'radiuskey1'}
${settings.radiusServer2 ? `radius-server host ${settings.radiusServer2 || '10.1.1.2'} key ${settings.radiusSecret2 || 'radiuskey2'}` : ''}

! AAA Configuration
aaa authentication port-access dot1x authenticator
aaa authentication dot1x default group radius local
aaa authentication mac-auth default group radius local
aaa authorization network default group radius
aaa accounting network start-stop group radius

! 802.1X Port Configuration
interface ${settings.interface || '1/1/1'}
 no routing
 vlan access ${settings.authVlan || '1'}
 dot1x authenticator
 dot1x authenticator port-control auto
 dot1x authenticator timeout quiet-period ${settings.quietPeriod || 60}
 dot1x authenticator timeout tx-period ${settings.txPeriod || 30}
 dot1x authenticator reauthentication
 dot1x authenticator timeout reauth-period ${settings.reauthPeriod || 3600}
${settings.authMethod === 'mab' || settings.authMethod === 'dot1x-mab' ? ' mac-auth' : ''}
${settings.voiceVlan ? ` voice-vlan ${settings.voiceVlan}` : ''}
 no shutdown
`;
        },
        
        'aos-switch': function(settings) {
            return `! Aruba AOS-Switch 802.1X Configuration
! Generated by Dot1Xer Supreme Enterprise Edition
!
! RADIUS Authentication Configuration
radius-server host ${settings.radiusServer1 || '10.1.1.1'} key ${settings.radiusSecret1 || 'radiuskey1'}
${settings.radiusServer2 ? `radius-server host ${settings.radiusServer2 || '10.1.1.2'} key ${settings.radiusSecret2 || 'radiuskey2'}` : ''}

! AAA Configuration
aaa authentication port-access eap-radius
aaa authentication dot1x default radius local
aaa authentication mac-auth default radius local
aaa authorization network default radius
aaa accounting network start-stop radius

! 802.1X Global Configuration
aaa port-access authenticator active
aaa port-access authenticator reauth-period ${settings.reauthPeriod || 3600}
aaa port-access authenticator quiet-period ${settings.quietPeriod || 60}
aaa port-access authenticator tx-period ${settings.txPeriod || 30}

! MAC Authentication Format
aaa port-access mac-auth addr-format no-delimiter
aaa port-access mac-auth addr-format uppercase

! Interface Configuration
interface ${settings.interface || '1/1'}
 aaa port-access authenticator active
 aaa port-access authenticator auth-vid ${settings.authVlan || '1'}
 aaa port-access authenticator unauth-vid ${settings.unauthVlan || '999'}
${settings.authMethod === 'mab' || settings.authMethod === 'dot1x-mab' ? ' aaa port-access mac-auth' : ''}
${settings.voiceVlan ? ` voice-vlan ${settings.voiceVlan}` : ''}
 spanning-tree admin-edge-port
 spanning-tree bpdu-protection
`;
        }
    },
    
    // Generate Juniper configurations
    juniper: {
        junos: function(settings) {
            return `# Juniper JunOS 802.1X Configuration
# Generated by Dot1Xer Supreme Enterprise Edition

system {
    radius-server {
        ${settings.radiusServer1 || '10.1.1.1'} {
            secret "${settings.radiusSecret1 || 'radiuskey1'}";
            timeout 5;
            retry 3;
            port 1812;
            accounting-port 1813;
        }
${settings.radiusServer2 ? `        ${settings.radiusServer2 || '10.1.1.2'} {
            secret "${settings.radiusSecret2 || 'radiuskey2'}";
            timeout 5;
            retry 3;
            port 1812;
            accounting-port 1813;
        }` : ''}
    }
}

access {
    profile dot1x-profile {
        authentication-order [${settings.authMethod === 'mab' ? 'mac-radius' : settings.authMethod === 'dot1x-mab' ? 'dot1x mac-radius' : 'dot1x'}];
        radius {
            authentication-server [${settings.radiusServer1 || '10.1.1.1'}${settings.radiusServer2 ? ' ' + settings.radiusServer2 : ''}];
            accounting-server [${settings.radiusServer1 || '10.1.1.1'}${settings.radiusServer2 ? ' ' + settings.radiusServer2 : ''}];
        }
        accounting {
            order radius;
            accounting-stop-on-failure;
            accounting-stop-on-access-deny;
        }
    }
}

protocols {
    dot1x {
        authenticator {
            authentication-profile-name dot1x-profile;
            interface {
                ${settings.interface || 'ge-0/0/0'} {
${settings.hostMode === 'multi-host' ? '                    supplicant multiple;' : 
  settings.hostMode === 'single-host' ? '                    supplicant single;' : 
  settings.hostMode === 'multi-auth' ? '                    supplicant multiple;' : 
  settings.hostMode === 'multi-domain' ? '                    supplicant multiple;' : 
  '                    supplicant multiple;'}
                    retries ${settings.maxReauth || 2};
                    quiet-period ${settings.quietPeriod || 60};
                    transmit-period ${settings.txPeriod || 30};
                    mac-radius {
                        restrict;
                    }
                    server-timeout 30;
                    supplicant-timeout 30;
                    reauthentication ${settings.reauthPeriod || 3600};
${settings.guestVlan ? `                    guest-vlan ${settings.guestVlan};` : ''}
${settings.unauthVlan ? `                    server-fail vlan-name ${settings.unauthVlan};` : ''}
                }
            }
        }
    }
}

vlans {
${settings.authVlan ? `    auth-vlan {
        vlan-id ${settings.authVlan};
    }` : ''}
${settings.unauthVlan ? `    unauth-vlan {
        vlan-id ${settings.unauthVlan};
    }` : ''}
${settings.guestVlan ? `    guest-vlan {
        vlan-id ${settings.guestVlan};
    }` : ''}
${settings.voiceVlan ? `    voice-vlan {
        vlan-id ${settings.voiceVlan};
    }` : ''}
}

# Interface Configuration
interfaces {
    ${settings.interface || 'ge-0/0/0'} {
        unit 0 {
            family ethernet-switching {
                interface-mode access;
                vlan {
                    members ${settings.authVlan || 'default'};
                }
${settings.voiceVlan ? `                voip {
                    vlan ${settings.voiceVlan};
                }` : ''}
            }
        }
    }
}
`;
        }
    },
    
    // Other vendor configurations would be added here
    
    // Default generic configuration
    generic: {
        default: function(settings) {
            return `# Generic 802.1X Configuration
# Generated by Dot1Xer Supreme Enterprise Edition
#
# Note: This is a generic configuration. Please refer to your vendor's
# documentation for specific syntax and commands.
#
# RADIUS Server: ${settings.radiusServer1 || 'Not configured'}
# Secondary RADIUS Server: ${settings.radiusServer2 || 'Not configured'}
#
# Authentication Method: ${settings.authMethod || 'dot1x'}
# Host Mode: ${settings.hostMode || 'single-host'}
#
# Authentication VLAN: ${settings.authVlan || 'Not configured'}
# Unauthenticated VLAN: ${settings.unauthVlan || 'Not configured'}
# Guest VLAN: ${settings.guestVlan || 'Not configured'}
# Voice VLAN: ${settings.voiceVlan || 'Not configured'}
#
# Interface: ${settings.interface || 'Not configured'}
#
# Reauthentication Period: ${settings.reauthPeriod || 3600} seconds
# Transmit Period: ${settings.txPeriod || 30} seconds
# Quiet Period: ${settings.quietPeriod || 60} seconds
# Maximum Retries: ${settings.maxReauth || 2}
`;
        }
    }
};

// Get configuration based on vendor and platform
function getVendorConfiguration(vendor, platform, settings) {
    // Check if vendor exists
    if (VendorConfigurators[vendor]) {
        // Check if platform exists for vendor
        if (VendorConfigurators[vendor][platform]) {
            return VendorConfigurators[vendor][platform](settings);
        }
        // Use default platform if specific one not found
        else if (VendorConfigurators[vendor]['default']) {
            return VendorConfigurators[vendor]['default'](settings);
        }
    }
    
    // Fall back to generic configuration
    return VendorConfigurators.generic.default(settings);
}
